language: node_js
node_js:
- '12'
script:
- yarn lint
- yarn test
- yarn build
cache: yarn
deploy:
  provider: npm
  skip_cleanup: true
  email: domoritz@gmail.com
  on:
    tags: true
    repo: vega/vega-tooltip
  api_key:
    secure: K/mRXQcKissi2f58DxA9CSi34mo1PZp8f+bgFYdBgnQk9HA6wTIjHt4jS1MuUvdWK+Z+Pnicup9V1o8fBFvhB5L0k5ZNHNw+41DBT59ajh3yaxa2kZiERHrKQhyFJ0B4/SlE6xPlG8pDGQ2EgLB52JaMteObJW8BjT6w/3WXVC/F9w/gqfh1b/5EHMn8mp4WbhHbkWWqMWQDP9uzWx3S4lnQMsmKfg+2sRmWUvor5B2htQvHls+3YNnIPkVGgV4EJS2fDO4TMAzxdzNA7uSMh1aMvWdODOpLFLLoyMKwTzRcnM5WgwDqu6OmXCBpshn4rO5/haGK5/xjEgfPC/SlHuMOFNJ4B/9VmmZ5WgAb4ZMCJXt0UYz6ITzFPuG/CQwXHq7dNhp+pwR+ogvAi4ixxLNiTSC3BfE9YTI76k5+z6UVY9eigid2arJ302NSxnyeDKQx8zg8aNzPUkvKW6QlNqc7Lg1o573Ai1ZhNNu4VAiLYV1UnAEbrK75wQxJFCjHRBjDogrRJ31grKRH6C794QZDc7Lbu0YKX8cZ2Nv/PefMjEWn6FSt1Ll6Lr9bClVqUcJ2bqnVy9xlmwMEZ6sswV9GZY2ea5vLnkF1T3UF/XJ19l9devzW7uz0DGggIOQyvgwZwSw5MWP/aCH5zuXnYS4aDgEedP0lGzTRZ59COvg=
